algo = input('Escreva algo')
print('O tipo primitivo desta variável é', type(algo))
print('A variável é alfanumérica?', algo.isalnum())
print('A variável é composta de letras?', algo.isalpha())
print('A variável está minuscula?', algo.islower())
print('A variável está maiuscula?', algo.isupper())
print('A variável é imprimivel?', algo.isprintable())
print('A variável é um numero?', algo.isnumeric())
print('A variável é espaços?', algo.isspace())
print('A variável está capitalizada?', algo.istitle)
