n = int(input('Digite o numero que você deseja ver a tabuada: '))
print('O numero {} X 1 é {}'.format(n, n*1))
print('O numero {} X 2 é {}'.format(n, n*2))
print('O numero {} X 3 é {}'.format(n, n*3))
print('O numero {} X 4 é {}'.format(n, n*4))
print('O numero {} X 5 é {}'.format(n, n*5))
print('O numero {} X 6 é {}'.format(n, n*6))
print('O numero {} X 7 é {}'.format(n, n*7))
print('O numero {} X 8 é {}'.format(n, n*8))
print('O numero {} X 9 é {}'.format(n, n*9))
print('O numero {} X 10 é {}'.format(n, n*10))
